# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: mpm 0.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "mpm".freeze
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Erik Nomitch".freeze]
  s.date = "2016-10-05"
  s.description = "A meta package manager to unify interaction with multiple package managers across various platforms.".freeze
  s.email = "erik@nomitch.com".freeze
  s.executables = ["mpm".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/mpm",
    "lib/mpm.rb",
    "lib/mpm/cli.rb",
    "lib/mpm/pm/extension.rb",
    "lib/mpm/pm/provisioner.rb",
    "lib/pm_provisioners/apt.rb",
    "lib/pm_provisioners/brew.rb",
    "lib/pm_provisioners/brew/cask.rb",
    "lib/pm_provisioners/extensions/npm.rb",
    "lib/pm_provisioners/extensions/pip.rb",
    "lib/pm_provisioners/ruby-gems/ruby-gems.rb",
    "mpm.gemspec",
    "ofe.json",
    "run",
    "test/helper.rb",
    "test/test_package.rb"
  ]
  s.homepage = "http://github.com/eriknomitch/mpm".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.6".freeze
  s.summary = "A meta package manager".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>.freeze, ["~> 4.2"])
      s.add_runtime_dependency(%q<thor>.freeze, ["~> 0.19"])
      s.add_runtime_dependency(%q<awesome_print>.freeze, ["~> 1.6"])
      s.add_runtime_dependency(%q<os>.freeze, ["~> 0.9"])
      s.add_runtime_dependency(%q<os-name>.freeze, ["~> 0.0"])
      s.add_runtime_dependency(%q<recursive-open-struct>.freeze, ["~> 0"])
      s.add_runtime_dependency(%q<colorize>.freeze, ["~> 0"])
      s.add_development_dependency(%q<shoulda>.freeze, ["~> 3.5"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>.freeze, ["= 1.12.0"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.0"])
      s.add_development_dependency(%q<simplecov>.freeze, ["~> 0"])
      s.add_development_dependency(%q<pry>.freeze, ["~> 0"])
    else
      s.add_dependency(%q<activesupport>.freeze, ["~> 4.2"])
      s.add_dependency(%q<thor>.freeze, ["~> 0.19"])
      s.add_dependency(%q<awesome_print>.freeze, ["~> 1.6"])
      s.add_dependency(%q<os>.freeze, ["~> 0.9"])
      s.add_dependency(%q<os-name>.freeze, ["~> 0.0"])
      s.add_dependency(%q<recursive-open-struct>.freeze, ["~> 0"])
      s.add_dependency(%q<colorize>.freeze, ["~> 0"])
      s.add_dependency(%q<shoulda>.freeze, ["~> 3.5"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<bundler>.freeze, ["= 1.12.0"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.0"])
      s.add_dependency(%q<simplecov>.freeze, ["~> 0"])
      s.add_dependency(%q<pry>.freeze, ["~> 0"])
    end
  else
    s.add_dependency(%q<activesupport>.freeze, ["~> 4.2"])
    s.add_dependency(%q<thor>.freeze, ["~> 0.19"])
    s.add_dependency(%q<awesome_print>.freeze, ["~> 1.6"])
    s.add_dependency(%q<os>.freeze, ["~> 0.9"])
    s.add_dependency(%q<os-name>.freeze, ["~> 0.0"])
    s.add_dependency(%q<recursive-open-struct>.freeze, ["~> 0"])
    s.add_dependency(%q<colorize>.freeze, ["~> 0"])
    s.add_dependency(%q<shoulda>.freeze, ["~> 3.5"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, ["= 1.12.0"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.0"])
    s.add_dependency(%q<simplecov>.freeze, ["~> 0"])
    s.add_dependency(%q<pry>.freeze, ["~> 0"])
  end
end

